// ==========================================
// SEED & INITIAL DEMO DATA FOR PERSONAL LIFE OS
// ==========================================

import type {
  User,
  MembershipPlan,
  Account,
  Transaction,
  Budget,
  JournalEntry,
  Activity,
  Task,
  Exercise,
  Workout,
  Habit,
  HabitLog,
  Goal,
  Achievement,
  TelegramIntegration,
  SystemAuditLog,
  SubscriptionHistoryItem,
  Coupon,
} from '../types';
import { getTodayString } from './formatters';

const today = getTodayString();

export const INITIAL_USERS: User[] = [
  {
    id: 'user-bintang',
    name: 'Bintang Mas',
    username: 'bintang',
    email: 'bintang@gmail.com',
    whatsapp: '+6281234567890',
    role: 'user',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    timezone: 'Asia/Jakarta',
    currency: 'IDR',
    membershipPlanId: 'yearly',
    membershipStartDate: '2026-08-01',
    membershipExpiryDate: '2027-08-01',
    onboardingCompleted: true,
    pinCode: '1234',
    createdAt: '2026-08-01T08:00:00Z',
    lastSeenAt: new Date().toISOString(),
  },
  {
    id: 'user-admin',
    name: 'Admin System',
    username: 'admin',
    email: 'admin@lifeos.com',
    whatsapp: '+6285869299537',
    role: 'super_admin',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    timezone: 'Asia/Jakarta',
    currency: 'IDR',
    membershipPlanId: 'lifetime',
    membershipStartDate: '2026-01-01',
    membershipExpiryDate: '2099-12-31',
    onboardingCompleted: true,
    createdAt: '2026-01-01T00:00:00Z',
    lastSeenAt: new Date().toISOString(),
  },
  {
    id: 'user-reza',
    name: 'Reza Pratama',
    username: 'reza',
    email: 'reza@outlook.com',
    whatsapp: '+6281122334455',
    role: 'user',
    status: 'active',
    timezone: 'Asia/Jakarta',
    currency: 'IDR',
    membershipPlanId: 'semi_annual',
    membershipStartDate: '2026-08-10',
    membershipExpiryDate: '2027-02-10',
    onboardingCompleted: true,
    createdAt: '2026-08-10T10:00:00Z',
    lastSeenAt: '2026-08-25T19:30:00Z',
  },
];

export const INITIAL_MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: 'free',
    name: 'Free Trial 7 Hari',
    priceFormatted: 'Rp0 (7 Hari)',
    priceMonthly: 0,
    durationDays: 7,
    features: [
      'Full Akses 100% Seluruh Fitur SaaS (7 Hari)',
      'Integrasi Bot Telegram AI Real-time',
      'Daily Journal & Solusi Refleksi AI',
      'Manajemen Keuangan Multi Rekening',
      'Gym & Workout Logger Lengkap',
      'Data 100% Aman Tersimpan Saat Trial Habis',
    ],
    limits: {
      aiAnalysis: true,
      advancedReports: true,
      telegramBot: true,
      gymModule: true,
      customCategories: true,
    },
  },
  {
    id: 'monthly',
    name: 'Paket 1 Bulan',
    priceFormatted: 'Rp10.000 / bln',
    priceMonthly: 10000,
    durationDays: 30,
    features: [
      'Full Akses 100% Seluruh Fitur (30 Hari)',
      'AI Personal Analyst & Solusi Jurnal',
      'Integrasi Bot Telegram AI Real-time',
      'Multi-Rekening & Budget Keuangan',
      'Gym Tracker, Habit Matrix & Tasks',
      'Export PDF, Excel & Backup Database',
    ],
    limits: {
      aiAnalysis: true,
      advancedReports: true,
      telegramBot: true,
      gymModule: true,
      customCategories: true,
    },
  },
  {
    id: 'semi_annual',
    name: 'Paket 6 Bulan',
    priceFormatted: 'Rp35.000 / 6 bln',
    priceMonthly: 5833,
    durationDays: 180,
    features: [
      'Full Akses 100% Seluruh Fitur (180 Hari)',
      'Hemat 42% dibanding bulanan (Hanya ~Rp5.800/bln)',
      'AI Personal Analyst & Rekomendasi Pintar',
      'Integrasi Bot Telegram AI 24/7',
      'Semua Modul Keuangan, Gym, Jurnal & Habit',
      'Prioritas WhatsApp Support Admin',
    ],
    limits: {
      aiAnalysis: true,
      advancedReports: true,
      telegramBot: true,
      gymModule: true,
      customCategories: true,
    },
  },
  {
    id: 'yearly',
    name: 'Paket 1 Tahun',
    priceFormatted: 'Rp50.000 / tahun',
    priceMonthly: 4166,
    durationDays: 365,
    features: [
      'Full Akses 100% Seluruh Fitur (365 Hari)',
      'Super Hemat 58% (Hanya ~Rp4.100/bln)',
      'AI Personal Analyst & Evaluasi Tahunan',
      'Integrasi Bot Telegram AI Tanpa Batas',
      'Seluruh Modul & Fitur Masa Depan',
      'Prioritas WhatsApp Support VIP',
    ],
    limits: {
      aiAnalysis: true,
      advancedReports: true,
      telegramBot: true,
      gymModule: true,
      customCategories: true,
    },
  },
  {
    id: 'lifetime',
    name: 'Lifetime VIP (Selamanya)',
    priceFormatted: 'Rp100.000 (Sekali Bayar)',
    priceMonthly: 0,
    durationDays: 36500,
    features: [
      'Full Akses 100% Selamanya (Seumur Hidup)',
      'Sekali Bayar Tanpa Biaya Bulanan Lagi',
      'Akses VIP Semua Update & Fitur Baru SaaS',
      'AI Personal Analyst & Telegram Bot Lifetime',
      'Prioritas Utama Fast-Track Support Admin',
      'Badge Eksklusif Golden VIP di Profil',
    ],
    limits: {
      aiAnalysis: true,
      advancedReports: true,
      telegramBot: true,
      gymModule: true,
      customCategories: true,
    },
  },
];

export const INITIAL_ACCOUNTS: Account[] = [
  { id: 'acc-1', userId: 'user-bintang', name: 'Dompet Cash', type: 'cash', balance: 450000, isActive: true, updatedAt: today },
  { id: 'acc-2', userId: 'user-bintang', name: 'Bank BCA Utama', type: 'bank', balance: 5200000, accountNumber: '8830192831', isActive: true, updatedAt: today },
  { id: 'acc-3', userId: 'user-bintang', name: 'Bank Mandiri Bisnis', type: 'bank', balance: 3400000, accountNumber: '1420019283', isActive: true, updatedAt: today },
  { id: 'acc-4', userId: 'user-bintang', name: 'GoPay & E-Wallet', type: 'ewallet', balance: 280000, isActive: true, updatedAt: today },
  { id: 'acc-5', userId: 'user-bintang', name: 'Tabungan Masa Depan', type: 'savings', balance: 18500000, isActive: true, updatedAt: today },
  { id: 'acc-6', userId: 'user-bintang', name: 'Dana Investasi Reksadana', type: 'investment', balance: 12000000, isActive: true, updatedAt: today },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    userId: 'user-bintang',
    type: 'expense',
    amount: 15000,
    category: 'Makanan & Minuman',
    description: 'Sarapan Nasi Uduk',
    sourceAccountId: 'acc-1',
    paymentMethod: 'Cash',
    date: today,
    time: '07:30:00',
    timestamp: `${today}T07:30:00Z`,
    tags: ['#food', '#breakfast'],
    createdAt: `${today}T07:30:00Z`,
    updatedAt: `${today}T07:30:00Z`,
  },
  {
    id: 'tx-2',
    userId: 'user-bintang',
    type: 'expense',
    amount: 10000,
    category: 'Makanan & Minuman',
    description: 'Kopi Kenangan via Telegram',
    sourceAccountId: 'acc-4',
    paymentMethod: 'GoPay',
    date: today,
    time: '10:15:00',
    timestamp: `${today}T10:15:00Z`,
    tags: ['#coffee', '#telegram'],
    createdAt: `${today}T10:15:00Z`,
    updatedAt: `${today}T10:15:00Z`,
  },
  {
    id: 'tx-3',
    userId: 'user-bintang',
    type: 'expense',
    amount: 25000,
    category: 'Makanan & Minuman',
    description: 'Makan Siang Ayam Geprek',
    sourceAccountId: 'acc-1',
    paymentMethod: 'Cash',
    date: today,
    time: '13:00:00',
    timestamp: `${today}T13:00:00Z`,
    tags: ['#lunch'],
    createdAt: `${today}T13:00:00Z`,
    updatedAt: `${today}T13:00:00Z`,
  },
  {
    id: 'tx-4',
    userId: 'user-bintang',
    type: 'expense',
    amount: 30000,
    category: 'Transportasi',
    description: 'Bensin Pertamax Motor',
    sourceAccountId: 'acc-1',
    paymentMethod: 'Cash',
    date: today,
    time: '16:45:00',
    timestamp: `${today}T16:45:00Z`,
    tags: ['#fuel'],
    createdAt: `${today}T16:45:00Z`,
    updatedAt: `${today}T16:45:00Z`,
  },
  {
    id: 'tx-5',
    userId: 'user-bintang',
    type: 'income',
    amount: 8500000,
    category: 'Pemasukan',
    description: 'Gaji Bulanan Software Engineer',
    sourceAccountId: 'acc-2',
    paymentMethod: 'Transfer Bank',
    date: '2026-08-25',
    time: '09:00:00',
    timestamp: '2026-08-25T09:00:00Z',
    tags: ['#salary', '#work'],
    createdAt: '2026-08-25T09:00:00Z',
    updatedAt: '2026-08-25T09:00:00Z',
  },
  {
    id: 'tx-6',
    userId: 'user-bintang',
    type: 'transfer',
    amount: 2000000,
    category: 'Transfer',
    description: 'Alokasi Tabungan Bulanan',
    sourceAccountId: 'acc-2',
    targetAccountId: 'acc-5',
    date: '2026-08-25',
    time: '10:00:00',
    timestamp: '2026-08-25T10:00:00Z',
    tags: ['#saving'],
    createdAt: '2026-08-25T10:00:00Z',
    updatedAt: '2026-08-25T10:00:00Z',
  },

  // ================= HISTORICAL TRANSACTIONS (JULI 2026) =================
  { id: 'tx-juli-1', userId: 'user-bintang', type: 'income', amount: 8500000, category: 'Pemasukan', description: 'Gaji Bulanan Juli', sourceAccountId: 'acc-2', date: '2026-07-25', time: '09:00:00', timestamp: '2026-07-25T09:00:00Z', tags: ['#salary'], createdAt: '2026-07-25T09:00:00Z', updatedAt: '2026-07-25T09:00:00Z' },
  { id: 'tx-juli-2', userId: 'user-bintang', type: 'expense', amount: 450000, category: 'Belanja & Kebutuhan', description: 'Beli Sepatu Gym Nike', sourceAccountId: 'acc-2', date: '2026-07-28', time: '14:30:00', timestamp: '2026-07-28T14:30:00Z', tags: ['#shopping'], createdAt: '2026-07-28T14:30:00Z', updatedAt: '2026-07-28T14:30:00Z' },
  { id: 'tx-juli-3', userId: 'user-bintang', type: 'expense', amount: 35000, category: 'Makanan & Minuman', description: 'Makan Malam Seafood', sourceAccountId: 'acc-1', date: '2026-07-20', time: '19:15:00', timestamp: '2026-07-20T19:15:00Z', tags: ['#dinner'], createdAt: '2026-07-20T19:15:00Z', updatedAt: '2026-07-20T19:15:00Z' },
  { id: 'tx-juli-4', userId: 'user-bintang', type: 'expense', amount: 150000, category: 'Kesehatan & Fitnes', description: 'Membership Gym Juli', sourceAccountId: 'acc-4', date: '2026-07-05', time: '10:00:00', timestamp: '2026-07-05T10:00:00Z', tags: ['#gym'], createdAt: '2026-07-05T10:00:00Z', updatedAt: '2026-07-05T10:00:00Z' },

  // ================= HISTORICAL TRANSACTIONS (JUNI 2026) =================
  { id: 'tx-juni-1', userId: 'user-bintang', type: 'income', amount: 8500000, category: 'Pemasukan', description: 'Gaji Bulanan Juni', sourceAccountId: 'acc-2', date: '2026-06-25', time: '09:00:00', timestamp: '2026-06-25T09:00:00Z', tags: ['#salary'], createdAt: '2026-06-25T09:00:00Z', updatedAt: '2026-06-25T09:00:00Z' },
  { id: 'tx-juni-2', userId: 'user-bintang', type: 'expense', amount: 120000, category: 'Transportasi', description: 'Servis Rutin Motor', sourceAccountId: 'acc-1', date: '2026-06-15', time: '11:00:00', timestamp: '2026-06-15T11:00:00Z', tags: ['#service'], createdAt: '2026-06-15T11:00:00Z', updatedAt: '2026-06-15T11:00:00Z' },
];

export const INITIAL_BUDGETS: Budget[] = [
  { id: 'b-1', userId: 'user-bintang', category: 'Makanan & Minuman', monthlyLimit: 1200000, period: '2026-08' },
  { id: 'b-2', userId: 'user-bintang', category: 'Transportasi', monthlyLimit: 500000, period: '2026-08' },
  { id: 'b-3', userId: 'user-bintang', category: 'Belanja & Kebutuhan', monthlyLimit: 800000, period: '2026-08' },
  { id: 'b-4', userId: 'user-bintang', category: 'Hiburan & Hobi', monthlyLimit: 400000, period: '2026-08' },
];

export const INITIAL_JOURNALS: JournalEntry[] = [
  {
    id: 'j-1',
    userId: 'user-bintang',
    date: today,
    title: 'Hari Yang Produktif & Terstruktur',
    content: 'Hari ini bangun jam 06:00 dengan segar. Latihan Chest + Triceps di gym berjalan sangat lancar, Bench Press berhasil naik ke 47.5kg. Pekerjaan fitur Telegram bot terselesaikan sesuai janji.',
    mood: 5,
    energyLevel: 8,
    stressLevel: 3,
    motivationLevel: 9,
    gratitudeText: 'Bersyukur diberikan kesehatan untuk gym dan pikiran yang jernih untuk coding.',
    learnedText: 'Pentingnya rest time 2 menit antar set heavy bench press.',
    problemsText: 'Sempat merasa haus di tengah latihan karena lupa membawa botol air tambahan.',
    solutionsText: 'Besok siapkan botol air 1.5 Liter sebelum berangkat ke gym.',
    highlightText: 'Selesai 5 dari 5 target task hari ini!',
    evaluationText: 'Secara umum produktivitas 90%, keuangan sangat hemat.',
    tomorrowPlanText: 'Latihan Back + Biceps jam 17:00, selesaikan review mingguan.',
    tags: ['#gym', '#productive', '#happy'],
    createdAt: `${today}T21:00:00Z`,
    updatedAt: `${today}T21:00:00Z`,
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  { id: 'act-1', userId: 'user-bintang', name: 'Bangun Pagi & Solat', category: 'productive', startTime: '06:00', endTime: '06:30', durationMinutes: 30, date: today, status: 'completed' },
  { id: 'act-2', userId: 'user-bintang', name: 'Sarapan & Ngopi', category: 'rest', startTime: '07:00', endTime: '07:45', durationMinutes: 45, date: today, status: 'completed' },
  { id: 'act-3', userId: 'user-bintang', name: 'Koding Project SaaS', category: 'work', startTime: '08:30', endTime: '12:00', durationMinutes: 210, date: today, status: 'completed' },
  { id: 'act-4', userId: 'user-bintang', name: 'Makan Siang & Istirahat', category: 'rest', startTime: '12:30', endTime: '13:30', durationMinutes: 60, date: today, status: 'completed' },
  { id: 'act-5', userId: 'user-bintang', name: 'Gym Workout (Chest & Triceps)', category: 'gym', startTime: '17:00', endTime: '18:15', durationMinutes: 75, date: today, status: 'completed' },
  { id: 'act-6', userId: 'user-bintang', name: 'Belajar React & AI Architecture', category: 'study', startTime: '19:30', endTime: '21:00', durationMinutes: 90, date: today, status: 'completed' },
  { id: 'act-7', userId: 'user-bintang', name: 'Tulis Journal Harian', category: 'productive', startTime: '21:15', endTime: '21:45', durationMinutes: 30, date: today, status: 'completed' },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 't-1',
    userId: 'user-bintang',
    title: 'Selesaikan Fitur Telegram Parser',
    description: 'Implementasi smart text recognition untuk Kopi 10k & Makan 25k bank',
    priority: 'high',
    status: 'done',
    category: 'Pengembangan SaaS',
    dueDate: today,
    checklist: [
      { id: 'st-1', title: 'Parse nominal k/jt/rb', completed: true },
      { id: 'st-2', title: 'Auto category mapping', completed: true },
      { id: 'st-3', title: 'Auto timestamp Telegram', completed: true },
    ],
    tags: ['#coding', '#urgent'],
    createdAt: `${today}T08:00:00Z`,
    updatedAt: `${today}T12:00:00Z`,
  },
  {
    id: 't-2',
    userId: 'user-bintang',
    title: 'Workout Gym: Chest & Triceps Day',
    description: 'Target Bench Press 47.5kg 3 sets',
    priority: 'high',
    status: 'done',
    category: 'Kesehatan & Gym',
    dueDate: today,
    dueTime: '17:00',
    checklist: [
      { id: 'st-4', title: 'Bench Press 3 sets', completed: true },
      { id: 'st-5', title: 'Incline Dumbbell Press 3 sets', completed: true },
      { id: 'st-6', title: 'Tricep Pushdown 4 sets', completed: true },
    ],
    tags: ['#gym', '#fitness'],
    createdAt: `${today}T08:00:00Z`,
    updatedAt: `${today}T18:15:00Z`,
  },
  {
    id: 't-3',
    userId: 'user-bintang',
    title: 'Review Budget Makanan Bulan Ini',
    description: 'Pastikan pengeluaran makanan masih di bawah batas Rp1.200.000',
    priority: 'medium',
    status: 'done',
    category: 'Keuangan',
    dueDate: today,
    checklist: [],
    tags: ['#finance'],
    createdAt: `${today}T08:00:00Z`,
    updatedAt: `${today}T15:00:00Z`,
  },
  {
    id: 't-4',
    userId: 'user-bintang',
    title: 'Membaca Buku Atomic Habits 20 Halaman',
    priority: 'low',
    status: 'todo',
    category: 'Self Improvement',
    dueDate: today,
    checklist: [],
    tags: ['#reading'],
    createdAt: `${today}T08:00:00Z`,
    updatedAt: `${today}T08:00:00Z`,
  },
];

export const EXERCISE_DATABASE: Exercise[] = [
  {
    id: 'ex-1',
    name: 'Barbell Bench Press',
    muscleGroup: 'Chest',
    difficulty: 'Menengah',
    equipment: 'Barbell & Flat Bench',
    targetMuscles: ['Dada Tengah (Pectoralis Major)', 'Triceps', 'Bahu Depan (Anterior Deltoid)'],
    description: 'Raja latihan dada untuk membangun ketebalan otot dada dan kekuatan dorong maksimal.',
    steps: [
      '1. SETUP: Berbaring di flat bench, mata sejajar di bawah barbel. Pijakkan kedua kaki kuat di lantai.',
      '2. GRIP & RETRAKSI: Pegang barbel sedikit lebih lebar dari bahu, tarik & kunci belikat (scapula retraction) ke bawah.',
      '3. TURUNKAN (ECCENTRIC): Turunkan barbel perlahan (2-3 detik) ke area puting/dada bawah dengan sudut siku 45-75 derajat.',
      '4. DORONG (CONCENTRIC): Dorong barbel naik dengan ledakan tenaga sambil menghembuskan napas hingga lengan lurus tanpa mengunci sendi siku berlebih.',
    ],
    commonMistakes: [
      '❌ Membuka siku 90 derajat terlalu lebar (berbahaya untuk sendi rotator cuff bahu).',
      '❌ Mengangkat bokong dari bench saat beban terasa berat.',
      '❌ Memantulkan barbel di tulang dada.',
    ],
    proTips: '💡 Bayangkan kamu sedang "mendorong lantai menjauh dengan kaki" (leg drive) untuk stabilitas tenaga ekstra!',
  },
  {
    id: 'ex-2',
    name: 'Incline Dumbbell Press',
    muscleGroup: 'Chest',
    difficulty: 'Pemula',
    equipment: 'Dumbbells & Incline Bench (30-45°)',
    targetMuscles: ['Dada Atas (Clavicular Head)', 'Bahu Depan', 'Triceps'],
    description: 'Latihan terbaik untuk mengisi otot dada bagian atas agar dada terlihat penuh dan 3D.',
    steps: [
      '1. Atur kemiringan bench ke sudut 30° hingga 45° (jangan terlalu tegak agar tidak dominan bahu).',
      '2. Angkat dumbbell ke dada, dorong ke atas hingga dumbbell berada di atas dada bagian atas.',
      '3. Turunkan dumbbell secara terkontrol rasakan regangan maksimal di serat otot dada atas.',
      '4. Peras (squeeze) otot dada atas saat mendorong kembali ke posisi puncak.',
    ],
    commonMistakes: [
      '❌ Sudut bench terlalu tegak (>60°) sehingga menjadi shoulder press.',
      '❌ Membenturkan dumbbell di posisi atas.',
    ],
    proTips: '💡 Jangan benturkan dumbbell di puncak; fokus pada meremas otot dada bagian atas!',
  },
  {
    id: 'ex-3',
    name: 'Chest Dip / Push Up',
    muscleGroup: 'Chest',
    difficulty: 'Pemula',
    equipment: 'Dip Station / Bodyweight Floor',
    targetMuscles: ['Dada Bawah', 'Triceps', 'Core'],
    description: 'Latihan calisthenics klasik untuk membentuk garis batas dada bawah yang tajam.',
    steps: [
      '1. Posisikan tubuh di palang dip, condongkan dada sedikit ke depan (lean forward 15-30°).',
      '2. Tekuk siku dan turunkan badan hingga siku membentuk sudut 90 derajat.',
      '3. Dorong badan kembali naik dengan mengontraksikan dada bawah dan triceps.',
    ],
    commonMistakes: [
      '❌ Badan terlalu tegak lurus (fokus akan pindah ke triceps murni bukan dada).',
      '❌ Turun terlalu dalam melebihi fleksibilitas bahu.',
    ],
    proTips: '💡 Condongkan badan ke depan dan tekuk lutut untuk fokus maksimal ke serat dada bawah!',
  },
  {
    id: 'ex-4',
    name: 'Lat Pulldown Wide Grip',
    muscleGroup: 'Back',
    difficulty: 'Pemula',
    equipment: 'Cable Lat Pulldown Machine',
    targetMuscles: ['Sayap Punggung (Latissimus Dorsi)', 'Biceps', 'Rhomboids'],
    description: 'Latihan nomor satu untuk membangun lebar punggung berbentuk V-Taper yang gagah.',
    steps: [
      '1. Duduk dengan paha terkunci di bantalan busa, pegang handle bar dengan grip lebar.',
      '2. Busungkan dada sedikit dan tarik bahu ke bawah (depress scapula).',
      '3. Tarik stang ke arah dada bagian atas sambil mengarahkan siku ke bawah dan belakang.',
      '4. Lepas stang naik perlahan rasakan otot sayap punggung meregang sempurna.',
    ],
    commonMistakes: [
      '❌ Mengayunkan badan ke belakang terlalu berlebihan (momentum).',
      '❌ Menarik stang ke belakang leher (sangat berbahaya untuk leher dan bahu).',
    ],
    proTips: '💡 Bayangkan kamu menarik dengan sikumu ke arah kantong celana belakang, bukan dengan telapak tangan!',
  },
  {
    id: 'ex-5',
    name: 'Seated Cable Row',
    muscleGroup: 'Back',
    difficulty: 'Pemula',
    equipment: 'Cable Row Machine with V-Bar',
    targetMuscles: ['Punggung Tengah (Rhomboids)', 'Lats', 'Trapezius Tengah'],
    description: 'Latihan untuk menambah ketebalan otot punggung dan memperbaiki postur tubuh bungkuk.',
    steps: [
      '1. Duduk tegak dengan lutut sedikit ditekuk, raih V-Bar dengan punggung lurus.',
      '2. Tarik handle ke arah pusar/perut bawah sambil meremas kedua belikat bersamaan.',
      '3. Tahan 1 detik kontraksi puncak di perut.',
      '4. Kembalikan beban ke depan secara terkontrol tanpa membungkukkan tulang belakang.',
    ],
    commonMistakes: [
      '❌ Membungkukkan punggung bawah saat meraih beban.',
      '❌ Menggunakan dorongan pinggang untuk menarik beban berat.',
    ],
    proTips: '💡 Tahan 1 detik di posisi puncak saat handle menyentuh perut untuk kontraksi punggung maksimal!',
  },
  {
    id: 'ex-6',
    name: 'Barbell Squat',
    muscleGroup: 'Legs',
    difficulty: 'Mahir',
    equipment: 'Barbell & Squat Rack',
    targetMuscles: ['Paha Depan (Quadriceps)', 'Bokong (Glutes)', 'Core', 'Hamstrings'],
    description: 'Raja dari seluruh latihan kaki dan kompond tubuh total untuk membakar kalori dan memicu hormon anabolik.',
    steps: [
      '1. Letakkan barbel di atas otot trapezius atas (upper back), berdiri dengan kaki selebar bahu.',
      '2. Tarik napas dalam ke perut (bracing core) dan kunci tulang belakang.',
      '3. Tekuk lutut dan dorong pinggul ke belakang seperti hendak duduk di kursi hingga paha minimal sejajar lantai (parallel depth).',
      '4. Dorong kembali naik dengan menekan seluruh telapak kaki ke lantai sambil membuang napas kuat.',
    ],
    commonMistakes: [
      '❌ Lutut menekuk ke dalam (knee valgus) saat mendorong naik.',
      '❌ Tumit terangkat dari lantai.',
      '❌ Punggung membungkuk (butt wink parah).',
    ],
    proTips: '💡 Kunci pernapasan di perut (Valsalva Maneuver) sebelum turun untuk melindungi tulang belakangmu!',
  },
  {
    id: 'ex-7',
    name: 'Leg Press',
    muscleGroup: 'Legs',
    difficulty: 'Pemula',
    equipment: 'Leg Press Machine 45°',
    targetMuscles: ['Paha Depan (Quadriceps)', 'Glutes'],
    description: 'Opsi latihan kaki yang sangat aman untuk mengangkat beban berat tanpa membebani tulang belakang.',
    steps: [
      '1. Duduk di mesin leg press dengan punggung dan bokong menempel rapat di bantalan.',
      '2. Tempatkan kaki di platform selebar bahu.',
      '3. Buka pengunci mesin, turunkan platform perlahan hingga lutut membentuk sudut 90 derajat.',
      '4. Dorong platform kembali naik TANPA mengunci lutut (jangan sampai lutut terkunci lurus 100%).',
    ],
    commonMistakes: [
      '❌ Mengunci lutut (lockout) di posisi atas (berbahaya untuk sendi lutut).',
      '❌ Mengangkat bokong dari kursi bantalan.',
    ],
    proTips: '💡 Jangan pernah mengunci lutut lurus saat beban di atas agar sendi lutut tetap aman 100%!',
  },
  {
    id: 'ex-8',
    name: 'Overhead Dumbbell Press',
    muscleGroup: 'Shoulders',
    difficulty: 'Menengah',
    equipment: 'Dumbbells & 90° Bench',
    targetMuscles: ['Bahu Depan (Anterior Deltoid)', 'Bahu Samping (Lateral Deltoid)', 'Triceps'],
    description: 'Membangun bahu lebar seperti buah kelapa (cannonball shoulders) dan kekuatan dorong vertikal.',
    steps: [
      '1. Duduk tegak di bench dengan punggung disandarkan rapat.',
      '2. Pegang dumbbell setinggi telinga dengan telapak tangan menghadap ke depan.',
      '3. Dorong dumbbell lurus ke atas kepala hingga lengan hampir lurus.',
      '4. Turunkan dumbbell perlahan ke posisi telinga.',
    ],
    commonMistakes: [
      '❌ Melengkungkan punggung bawah berlebihan.',
      '❌ Membanting dumbbell saat turun.',
    ],
    proTips: '💡 Kunci otot perut (core) agar pinggang tidak melengkung saat beban didorong ke atas!',
  },
  {
    id: 'ex-9',
    name: 'Dumbbell Lateral Raise',
    muscleGroup: 'Shoulders',
    difficulty: 'Pemula',
    equipment: 'Dumbbells',
    targetMuscles: ['Bahu Samping (Lateral Deltoid)'],
    description: 'Kunci utama untuk mendapatkan bahu samping yang lebar dan siluet tubuh proporsional.',
    steps: [
      '1. Berdiri tegak atau sedikit condong ke depan, pegang dumbbell di samping paha.',
      '2. Angkat dumbbell ke samping dengan siku sedikit ditekuk hingga sejajar tinggi bahu.',
      '3. Arahkan kelingking sedikit lebih tinggi dari jempol seperti menuangkan air teko.',
      '4. Turunkan secara perlahan (2 detik) tanpa mengayunkan badan.',
    ],
    commonMistakes: [
      '❌ Menggunakan beban terlalu berat sehingga mengayunkan pinggang.',
      '❌ Mengangkat lengan lebih tinggi dari bahu menggunakan otot leher (traps).',
    ],
    proTips: '💡 Gunakan beban ringan yang terkontrol. Pikirkan mendorong beban ke arah dinding samping, bukan ke atas!',
  },
  {
    id: 'ex-10',
    name: 'Barbell Bicep Curl',
    muscleGroup: 'Arms',
    difficulty: 'Pemula',
    equipment: 'EZ-Bar / Straight Barbell',
    targetMuscles: ['Biceps Brachii', 'Brachialis'],
    description: 'Latihan dasar pembentuk puncak dan kepalan otot lengan biceps depan.',
    steps: [
      '1. Berdiri tegak, pegang barbel dengan grip selebar bahu dan telapak menghadap ke atas.',
      '2. Rapatkan siku ke samping pinggang (jangan biarkan siku maju mundur).',
      '3. Tekuk siku dan angkat barbel ke arah dada sambil meremas puncak biceps.',
      '4. Turunkan barbel perlahan ke posisi awal dengan kendali penuh.',
    ],
    commonMistakes: [
      '❌ Mengayunkan tubuh ke belakang untuk mengangkat beban berat.',
      '❌ Membuka siku melebar dari pinggang.',
    ],
    proTips: '💡 Kunci posisi siku menempel di samping pinggang agar beban 100% diangkat oleh otot biceps!',
  },
  {
    id: 'ex-11',
    name: 'Tricep Rope Pushdown',
    muscleGroup: 'Arms',
    difficulty: 'Pemula',
    equipment: 'Cable Machine with Rope Attachment',
    targetMuscles: ['Triceps Lateral Head & Long Head'],
    description: 'Membentuk tapal kuda triceps di bagian belakang lengan (70% dari volume total lengan).',
    steps: [
      '1. Pasang tali (rope) di katrol atas cable machine.',
      '2. Condongkan badan sedikit ke depan dan kunci kedua siku di samping tulang rusuk.',
      '3. Dorong tali ke bawah dan bentangkan kedua ujung tali ke samping di bagian bawah.',
      '4. Rasakan kontraksi triceps maksimal 1 detik sebelum kembali naik perlahan ke sudut 90°.',
    ],
    commonMistakes: [
      '❌ Siku bergerak naik turun mengikuti tali.',
      '❌ Bahu ikut mendorong beban.',
    ],
    proTips: '💡 Buka/rentangkan ujung tali ke arah luar di bagian terbawah untuk kontraksi triceps paling tajam!',
  },
];

export const INITIAL_WORKOUTS: Workout[] = [
  {
    id: 'w-1',
    userId: 'user-bintang',
    date: today,
    startTime: '17:00',
    endTime: '18:15',
    durationMinutes: 75,
    workoutType: 'Chest + Triceps',
    muscleGroups: ['Chest', 'Arms'],
    exerciseLogs: [
      {
        id: 'el-1',
        exerciseId: 'ex-1',
        exerciseName: 'Barbell Bench Press',
        muscleGroup: 'Chest',
        sets: [
          { id: 's-1', setNumber: 1, reps: 10, weightKg: 40, rpe: 7 },
          { id: 's-2', setNumber: 2, reps: 8, weightKg: 45, rpe: 8 },
          { id: 's-3', setNumber: 3, reps: 6, weightKg: 47.5, rpe: 9 },
        ],
        notes: 'Personal Record baru di 47.5kg!',
      },
      {
        id: 'el-2',
        exerciseId: 'ex-2',
        exerciseName: 'Incline Dumbbell Press',
        muscleGroup: 'Chest',
        sets: [
          { id: 's-4', setNumber: 1, reps: 10, weightKg: 16, rpe: 7 },
          { id: 's-5', setNumber: 2, reps: 8, weightKg: 18, rpe: 8 },
        ],
      },
      {
        id: 'el-3',
        exerciseId: 'ex-11',
        exerciseName: 'Tricep Rope Pushdown',
        muscleGroup: 'Arms',
        sets: [
          { id: 's-6', setNumber: 1, reps: 12, weightKg: 20, rpe: 8 },
          { id: 's-7', setNumber: 2, reps: 10, weightKg: 25, rpe: 9 },
        ],
      },
    ],
    notes: 'Sangat puas dengan performa bench press hari ini.',
    createdAt: `${today}T18:15:00Z`,
  },
  {
    id: 'w-juli-1',
    userId: 'user-bintang',
    date: '2026-07-28',
    startTime: '17:00',
    durationMinutes: 60,
    workoutType: 'Back & Biceps Day',
    muscleGroups: ['Back', 'Arms'],
    exerciseLogs: [
      {
        id: 'el-juli-1',
        exerciseId: 'ex-4',
        exerciseName: 'Lat Pulldown Wide Grip',
        muscleGroup: 'Back',
        sets: [
          { id: 'sj-1', setNumber: 1, reps: 12, weightKg: 45 },
          { id: 'sj-2', setNumber: 2, reps: 10, weightKg: 50 },
        ],
      },
    ],
    createdAt: '2026-07-28T18:00:00Z',
  },
  {
    id: 'w-juli-2',
    userId: 'user-bintang',
    date: '2026-07-15',
    startTime: '16:30',
    durationMinutes: 70,
    workoutType: 'Leg Day Heavy Squat',
    muscleGroups: ['Legs'],
    exerciseLogs: [
      {
        id: 'el-juli-2',
        exerciseId: 'ex-6',
        exerciseName: 'Barbell Squat',
        muscleGroup: 'Legs',
        sets: [
          { id: 'sj-3', setNumber: 1, reps: 10, weightKg: 60 },
          { id: 'sj-4', setNumber: 2, reps: 8, weightKg: 70 },
        ],
      },
    ],
    createdAt: '2026-07-15T17:40:00Z',
  },
];

export const INITIAL_HABITS: Habit[] = [
  { id: 'h-1', userId: 'user-bintang', name: 'Bangun Pagi Jam 06:00', category: 'Disiplin', frequency: 'daily', icon: 'Sun', color: '#f59e0b', createdAt: today },
  { id: 'h-2', userId: 'user-bintang', name: 'Workout / Gym 45 Menit', category: 'Kesehatan', frequency: 'daily', icon: 'Dumbbell', color: '#ef4444', createdAt: today },
  { id: 'h-3', userId: 'user-bintang', name: 'Belajar Coding / Reading 1 Jam', category: 'Produktif', frequency: 'daily', icon: 'BookOpen', color: '#3b82f6', createdAt: today },
  { id: 'h-4', userId: 'user-bintang', name: 'Catat Jurnal & Review Malam', category: 'Refleksi', frequency: 'daily', icon: 'Edit3', color: '#10b981', createdAt: today },
  { id: 'h-5', userId: 'user-bintang', name: 'Minum Air 2.5 Liter', category: 'Kesehatan', frequency: 'daily', icon: 'Droplet', color: '#06b6d4', createdAt: today },
];

export const INITIAL_HABIT_LOGS: HabitLog[] = [
  { id: 'hl-1', habitId: 'h-1', userId: 'user-bintang', date: today, completed: true },
  { id: 'hl-2', habitId: 'h-2', userId: 'user-bintang', date: today, completed: true },
  { id: 'hl-3', habitId: 'h-3', userId: 'user-bintang', date: today, completed: true },
  { id: 'hl-4', habitId: 'h-4', userId: 'user-bintang', date: today, completed: true },
  { id: 'hl-5', habitId: 'h-5', userId: 'user-bintang', date: today, completed: false },
];

export const INITIAL_GOALS: Goal[] = [
  {
    id: 'g-1',
    userId: 'user-bintang',
    title: 'Dana Darurat & Investasi Rp100.000.000',
    type: 'finance',
    targetValue: 100000000,
    currentValue: 30500000,
    unit: 'IDR',
    deadline: '2027-12-31',
    milestones: [
      { id: 'm-1', title: 'Kumpulkan Rp10 Juta', completed: true },
      { id: 'm-2', title: 'Kumpulkan Rp30 Juta', completed: true },
      { id: 'm-3', title: 'Kumpulkan Rp50 Juta', completed: false },
      { id: 'm-4', title: 'Kumpulkan Rp100 Juta', completed: false },
    ],
    status: 'in_progress',
    createdAt: '2026-01-01',
  },
  {
    id: 'g-2',
    userId: 'user-bintang',
    title: 'Target Bench Press 60kg 1 Rep Max',
    type: 'gym',
    targetValue: 60,
    currentValue: 47.5,
    unit: 'kg',
    deadline: '2026-11-30',
    milestones: [
      { id: 'm-5', title: 'Angkat 40kg x 10', completed: true },
      { id: 'm-6', title: 'Angkat 47.5kg x 6', completed: true },
      { id: 'm-7', title: 'Angkat 52.5kg x 5', completed: false },
      { id: 'm-8', title: 'Angkat 60kg x 1', completed: false },
    ],
    status: 'in_progress',
    createdAt: '2026-06-01',
  },
  {
    id: 'g-3',
    userId: 'user-bintang',
    title: 'Journaling 365 Hari Tanpa Terputus',
    type: 'personal',
    targetValue: 365,
    currentValue: 45,
    unit: 'Hari',
    deadline: '2027-08-01',
    milestones: [
      { id: 'm-9', title: '7 Hari Streak', completed: true },
      { id: 'm-10', title: '30 Hari Streak', completed: true },
      { id: 'm-11', title: '100 Hari Streak', completed: false },
      { id: 'm-12', title: '365 Hari Streak', completed: false },
    ],
    status: 'in_progress',
    createdAt: '2026-07-01',
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  { id: 'ach-1', code: 'JOURNAL_7', title: '7 Day Journal Streak', description: 'Tulis jurnal harian selama 7 hari berturut-turut', icon: 'BookOpen', category: 'journal', unlockedAt: '2026-08-07' },
  { id: 'ach-2', code: 'JOURNAL_30', title: '30 Day Journal Master', description: 'Tulis jurnal harian selama 30 hari berturut-turut', icon: 'Award', category: 'journal', unlockedAt: '2026-08-20' },
  { id: 'ach-3', code: 'GYM_10', title: '10x Workout Conqueror', description: 'Selesaikan 10 sesi latihan gym', icon: 'Dumbbell', category: 'gym', unlockedAt: '2026-08-15' },
  { id: 'ach-4', code: 'BUDGET_MASTER', title: 'Budget Master', description: 'Tidak melebihi batas budget kategori selama 1 bulan', icon: 'ShieldCheck', category: 'finance', unlockedAt: '2026-07-31' },
  { id: 'ach-5', code: 'TASKS_100', title: '100 Tasks Done', description: 'Selesaikan total 100 task produktif', icon: 'CheckCircle', category: 'tasks' },
  { id: 'ach-6', code: 'SAVING_STREAK', title: 'Saving Streak Champion', description: 'Transfer tabungan 3 bulan berturut-turut', icon: 'TrendingUp', category: 'finance', unlockedAt: '2026-08-01' },
];

export const INITIAL_TELEGRAM_INTEGRATION: TelegramIntegration = {
  id: 'tg-1',
  userId: 'user-bintang',
  telegramUserId: '987654321',
  telegramChatId: '987654321',
  telegramUsername: '@bintang_mas',
  status: 'connected',
  connectionCode: 'A7K92P',
  connectedAt: '2026-08-02T10:00:00Z',
  lastMessageAt: `${today}T10:15:00Z`,
  settings: {
    notificationsEnabled: true,
    morningBriefing: true,
    morningBriefingTime: '07:00',
    nightlyReview: true,
    nightlyReviewTime: '21:00',
    expenseConfirmation: true,
    budgetWarning: true,
    taskReminder: true,
    gymReminder: true,
    membershipWarning: true,
    weeklyReport: true,
  },
};

export const INITIAL_AUDIT_LOGS: SystemAuditLog[] = [
  { id: 'al-1', adminId: 'user-admin', adminName: 'Admin System', action: 'Activate Membership', targetUserId: 'user-bintang', targetUserName: 'Bintang Mas', metadata: 'Plan: Premium (30 days extension)', timestamp: '2026-08-01T09:00:00Z' },
  { id: 'al-2', adminId: 'user-admin', adminName: 'Admin System', action: 'Extend Membership', targetUserId: 'user-reza', targetUserName: 'Reza Pratama', metadata: 'Plan: Basic (+30 days via WhatsApp)', timestamp: '2026-08-10T11:30:00Z' },
];

export const INITIAL_COUPONS: Coupon[] = [
  { id: 'c-1', code: 'PREMIUM30', discountPercentage: 30, bonusDays: 7, expiryDate: '2026-12-31', maxUsage: 100, usageCount: 14, status: 'active' },
  { id: 'c-2', code: 'NEWUSER7', discountPercentage: 0, bonusDays: 7, expiryDate: '2026-12-31', maxUsage: 500, usageCount: 82, status: 'active' },
];

export const INITIAL_SUBSCRIPTION_HISTORY: SubscriptionHistoryItem[] = [
  { id: 'sh-1', userId: 'user-bintang', planId: 'premium', planName: 'Premium OS', startDate: '2026-08-01', expiryDate: '2026-08-31', status: 'active', activatedBy: 'Admin System', createdAt: '2026-08-01T09:00:00Z' },
  { id: 'sh-2', userId: 'user-bintang', planId: 'premium', planName: 'Premium OS', startDate: '2026-09-01', expiryDate: '2026-09-30', status: 'extended', activatedBy: 'Admin System', createdAt: '2026-08-15T14:00:00Z' },
];

export const INITIAL_RECURRING_SUBSCRIPTIONS: import('../types').RecurringSubscription[] = [
  { id: 'sub-1', userId: 'user-bintang', name: 'Spotify Premium Family', amount: 86900, billingCycle: 'monthly', billingDay: 5, category: 'Hiburan', paymentMethod: 'BCA', icon: 'Music', isActive: true, notes: 'Auto-debet tanggal 5 tiap bulan', createdAt: '2026-08-01' },
  { id: 'sub-2', userId: 'user-bintang', name: 'Netflix 4K UHD', amount: 186000, billingCycle: 'monthly', billingDay: 18, category: 'Hiburan', paymentMethod: 'Kartu Kredit', icon: 'Tv', isActive: true, notes: 'Langganan shared account', createdAt: '2026-08-01' },
  { id: 'sub-3', userId: 'user-bintang', name: 'iCloud 200GB Storage', amount: 45000, billingCycle: 'monthly', billingDay: 28, category: 'Utilitas', paymentMethod: 'GoPay', icon: 'Cloud', isActive: true, notes: 'Backup iPhone & MacBook', createdAt: '2026-08-01' },
  { id: 'sub-4', userId: 'user-bintang', name: 'Gym Membership Gold', amount: 350000, billingCycle: 'monthly', billingDay: 1, category: 'Kesehatan', paymentMethod: 'BCA', icon: 'Dumbbell', isActive: true, notes: 'Akses 24/7 fitness center', createdAt: '2026-08-01' },
];

export const INITIAL_DEBTS: import('../types').DebtItem[] = [
  { id: 'debt-1', userId: 'user-bintang', type: 'receivable', personName: 'Andi Saputra', amount: 500000, paidAmount: 200000, dueDate: '2026-09-15', notes: 'Pinjam untuk servis motor', status: 'partial', createdAt: '2026-08-10', updatedAt: '2026-08-20' },
  { id: 'debt-2', userId: 'user-bintang', type: 'payable', personName: 'Toko Elektronik Makmur', amount: 1200000, paidAmount: 1200000, dueDate: '2026-08-25', notes: 'Cicilan monitor 27 inch 0%', status: 'settled', createdAt: '2026-07-25', updatedAt: '2026-08-25' },
  { id: 'debt-3', userId: 'user-bintang', type: 'receivable', personName: 'Budi Santoso', amount: 150000, paidAmount: 0, dueDate: '2026-09-05', notes: 'Talangan makan bareng di Resto', status: 'unpaid', createdAt: '2026-08-29', updatedAt: '2026-08-29' },
];

export const INITIAL_REWARDS: import('../types').PersonalReward[] = [
  { id: 'rew-1', userId: 'user-bintang', title: 'Secangkir Kopi Premium di Kafe', costCoins: 150, icon: 'Coffee', description: 'Self reward nikmat setelah 7 hari streak jurnal penuh', isClaimed: false, category: 'Food & Drink', createdAt: '2026-08-01' },
  { id: 'rew-2', userId: 'user-bintang', title: 'Main Game Favorit 2 Jam Bebas', costCoins: 200, icon: 'Gamepad2', description: 'Waktu santai main tanpa rasa bersalah', isClaimed: false, category: 'Gaming', createdAt: '2026-08-01' },
  { id: 'rew-3', userId: 'user-bintang', title: 'Nonton Film Bioskop Weekend', costCoins: 350, icon: 'Film', description: 'Nonton film premier di XXI / CGV', isClaimed: false, category: 'Entertainment', createdAt: '2026-08-01' },
  { id: 'rew-4', userId: 'user-bintang', title: 'Beli Buku Baru / Audiobook', costCoins: 500, icon: 'BookOpen', description: 'Investasi ilmu dan pengembangan diri', isClaimed: false, category: 'Self Growth', createdAt: '2026-08-01' },
  { id: 'rew-5', userId: 'user-bintang', title: 'Cheat Meal All-You-Can-Eat', costCoins: 800, icon: 'Utensils', description: 'Makan puas sepuasnya setelah konsisten gym 30 hari', isClaimed: false, category: 'Food & Drink', createdAt: '2026-08-01' },
];

export const INITIAL_AI_SETTINGS: import('../types').AISettings = {
  geminiApiKey: '',
  isGeminiActive: false,
  customCoachPersona: 'Bijak, Empatis, Tegas, dan Berorientasi pada Pertumbuhan Diri',
};

